### ISSUE TITLE
download trained weights and evaluate

### ISSUE THREAD

**Issue by erezposner** [dessa-public/DeepFake-Detection#11]
Hi, are the trained weights from you experiments on both dataset available for download?

**Comment by epiqueras** [comment]
Did you find it somewhere?

**Comment by epiqueras** [comment]
@erezposner

**Comment by erezposner** [comment]
@epiqueras, I think so but to tell you the truth, I cannot remember.

I do remember that training was fairly easy and quick so it is a viable option if you won't find the weights.

**Comment by epiqueras** [comment]
I'm on a Mac, so I would have to rent out a machine.

**Comment by erezposner** [comment]
“We live and die by our choices"

**Comment by epiqueras** [comment]
Hahaha, it's the best choice for everything else I do :smile:
