### ISSUE TITLE
CMAKE  is missing 

### ISSUE THREAD

**Issue by erezposner** [dessa-public/DeepFake-Detection#12]
please close

**Comment by svileng** [comment]
@erezposner I'm also getting a RuntimeError when running the container, failing to install `dlib` because of `cmake`.

How did you solve this? I've added `RUN apt-get install -y cmake` before the `pip install` step, but that doesn't seem to make a difference 🤔 Thanks for your help 👍

**Comment by erezposner** [comment]
My issue was a silly one. running cmake at the wrong directory.
