### ISSUE TITLE
foundations.submit broken

### ISSUE THREAD

**Issue by huang-da** [dessa-public/DeepFake-Detection#3]
Hi,

I'm using your custom_docker_image to repeat your experiment done on https://www.dessa.com/post/deepfake-detection-that-actually-works. However, the Foundations package I found on pypi does not seem to have a .submit member and I can't find an other foundations module that does contain this member. 

It's regarding this section in hparams_search.py.

`for job_ in range(NUM_JOBS):
    print "packaging job " + str(job_)
    hyper_params = generate_params()
    print hyper_params
    Foundations.submit(scheduler_config='scheduler', job_directory='.', command='main.py', params=hyper_params,
                       stream_job_logs=False)
`

**Comment by emilyed66** [comment]
@huang-da I am experiencing the same issue. Could you please advise how you resolved this? Thanks
