### ISSUE TITLE
Youtube Video URL?

### ISSUE THREAD

**Issue by yaoxx151** [dessa-public/DeepFake-Detection#7]
Hi, thanks for creating this repository. Is it possible to provide a list of URLs of DeepFake videos downloaded from Youtube? Thanks!

**Comment by Rayhane-mamah** [comment]
Hi,

Thank you for reaching out. Sadly, we don't keep a record of the exact URLs of the youtube videos used to extract the Youtube data, there was a bit of a manual process in both collection and cleaning (mostly clipping and selection of relevant clips).

I hope this answers your question. Please feel free to ask if you have any other concerns!
